model_name: "facebook/mbart-large-50"

languages:
  source: "en_XX"
  targets:
    - "es_XX"
    - "fr_XX"
    - "de_DE"

training_args:
  output_dir: "./results"
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  learning_rate: 5e-5
  evaluation_strategy: "epoch"
  save_total_limit: 2
  predict_with_generate: true
  fp16: true
